// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_jo2k4CwuheQWzI76mmWU3lKg-JM3Ms',
    appId: '1:1060188378643:web:0a23b9c8f2862e553651e6',
    messagingSenderId: '1060188378643',
    projectId: 'rockyconnectdriver',
    authDomain: 'rockyconnectdriver.firebaseapp.com',
    storageBucket: 'rockyconnectdriver.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAylfl6ez9nxIsiSzBvfjASRPZthbnOMts',
    appId: '1:1060188378643:android:947642c11ecf272b3651e6',
    messagingSenderId: '1060188378643',
    projectId: 'rockyconnectdriver',
    storageBucket: 'rockyconnectdriver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGpBB7Ekak5BTMojEY8o5yYEPPzhP13E0',
    appId: '1:1060188378643:ios:ac2aad0dd00a52df3651e6',
    messagingSenderId: '1060188378643',
    projectId: 'rockyconnectdriver',
    storageBucket: 'rockyconnectdriver.appspot.com',
    iosBundleId: 'com.example.rockyconnectdriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGpBB7Ekak5BTMojEY8o5yYEPPzhP13E0',
    appId: '1:1060188378643:ios:6ea6793cd2e769d33651e6',
    messagingSenderId: '1060188378643',
    projectId: 'rockyconnectdriver',
    storageBucket: 'rockyconnectdriver.appspot.com',
    iosBundleId: 'com.example.rockyconnectdriver.RunnerTests',
  );
}
